---
- hosts: all
  roles:
  - oefenweb.ssh_keys
  vars:
    ssh_keys_public_keys:
      - owner: root
        src: keys/davidfic_jupiter.pub 
    ssh_keys_authorized_keys:
      - owner: root
        src: keys/davidfic_jupiter.pub
    ssh_keys_authorized_keys:
      - owner: root
        src: keys/davidfic_jupiter.pub




